name: bookia_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  flutter_toggle_tab: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/translation/

  fonts:
    - family: DMSerif
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf

